### ISSUE TITLE
Are there any GUI interface tools available to assist in generating scene description XML files？

### ISSUE THREAD

**Issue by xuarehere** [AutonomousDrivingExaminer/mats-gym#1]
This is an amazing job, thank you to the author for their open source efforts. 

I want to create more test cases,Are there any GUI interface tools available to assist in generating scene description XML files？ Like this:
```
scenarios/scenario-runner/CutIn.xml
```

**Comment by axelbr** [comment]
Thank you!
There are graphical user interfaces for editing OpenScenario files ([https://github.com/ebadi/OpenScenarioEditor](https://github.com/ebadi/OpenScenarioEditor)). I dont know of any for ScenarioRunner files, but I did not conduct an exhaustive search.
